<?php

namespace jobseeker\Bundle\CareerBundle\Entity;

/**
 * SendCVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendCVRepository extends \Doctrine\ORM\EntityRepository
{

    public function isAvailable($jid, $emrid, $sessionid, $hydration = 2)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->add("select", "s")
                ->add("from", "CareerBundle:SendCV s")
                ->add("where", "s.jid = :jid and s.emr = :emr and s.sessionid = :sessionid")
                ->setParameter("jid", $jid)
                ->setParameter("emr", $emrid)
                ->setParameter("sessionid", $sessionid);

        return $qb->getQuery()->getResult($hydration);
    }

}
